In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('car_evaluation - car_evaluation.csv')
df.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [3]:
df.shape

(1727, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   vhigh    1727 non-null   object
 1   vhigh.1  1727 non-null   object
 2   2        1727 non-null   object
 3   2.1      1727 non-null   object
 4   small    1727 non-null   object
 5   low      1727 non-null   object
 6   unacc    1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [5]:
col_name=['buying','maint','doors','persons','lug_boot','safety','class']
df.columns=col_name
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [6]:
df.shape

(1727, 7)

In [7]:
df['buying'].value_counts()

high     432
med      432
low      432
vhigh    431
Name: buying, dtype: int64

In [8]:
for i in df.columns:
    print(i,':\n',df[i].value_counts())

buying :
 high     432
med      432
low      432
vhigh    431
Name: buying, dtype: int64
maint :
 high     432
med      432
low      432
vhigh    431
Name: maint, dtype: int64
doors :
 3        432
4        432
5more    432
2        431
Name: doors, dtype: int64
persons :
 4       576
more    576
2       575
Name: persons, dtype: int64
lug_boot :
 med      576
big      576
small    575
Name: lug_boot, dtype: int64
safety :
 med     576
high    576
low     575
Name: safety, dtype: int64
class :
 unacc    1209
acc       384
good       69
vgood      65
Name: class, dtype: int64


## FEATURE ENGINEERING

In [9]:
import category_encoders as cate

In [10]:
encode=cate.OrdinalEncoder(cols=['buying','maint','doors','persons','lug_boot','safety'])
df=encode.fit_transform(df)

In [11]:
for i in df.columns:
    print(i,':\n',df[i].value_counts())

buying :
 2    432
3    432
4    432
1    431
Name: buying, dtype: int64
maint :
 2    432
3    432
4    432
1    431
Name: maint, dtype: int64
doors :
 2    432
3    432
4    432
1    431
Name: doors, dtype: int64
persons :
 2    576
3    576
1    575
Name: persons, dtype: int64
lug_boot :
 2    576
3    576
1    575
Name: lug_boot, dtype: int64
safety :
 1    576
2    576
3    575
Name: safety, dtype: int64
class :
 unacc    1209
acc       384
good       69
vgood      65
Name: class, dtype: int64


In [12]:
encode=cate.OrdinalEncoder(cols=['class'])
df=encode.fit_transform(df)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1727 non-null   int32
 1   maint     1727 non-null   int32
 2   doors     1727 non-null   int32
 3   persons   1727 non-null   int32
 4   lug_boot  1727 non-null   int32
 5   safety    1727 non-null   int32
 6   class     1727 non-null   int32
dtypes: int32(7)
memory usage: 47.3 KB


In [14]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1:]

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rf=RandomForestClassifier(n_estimators=100,random_state=0)

In [19]:
rf.fit(X_train,Y_train)
y_pred=rf.predict(X_test)

C:\Users\aakas\AppData\Local\Temp\ipykernel_1512\2544060147.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train,Y_train)


In [20]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy_score(Y_test,y_pred)

0.976878612716763

In [22]:
from sklearn.metrics import confusion_matrix,classification_report

In [23]:
print(confusion_matrix(Y_test,y_pred,labels=[1,2,3,4]))


[[353   8   0   0]
 [  1 112   0   0]
 [  0   1  21   2]
 [  0   0   0  21]]


In [24]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      0.98      0.99       361
           2       0.93      0.99      0.96       113
           3       1.00      0.88      0.93        24
           4       0.91      1.00      0.95        21

    accuracy                           0.98       519
   macro avg       0.96      0.96      0.96       519
weighted avg       0.98      0.98      0.98       519

